### ISSUE TITLE
Can't capture CSV from a DS1054Z on Mac OS

### ISSUE THREAD

**Issue by mlemos** [RoGeorge/DS1054Z_screen_capture#5]
Hi,

I just installed your software and it worked just fine to capture PNG files.

However, when I try to capture CSV I get the following error messages:

$ python OscScreenGrabLAN.py csv 10.0.1.104
Instrument ID: RIGOL TECHNOLOGIES,DS1054Z,DS1ZA180300357,00.04.03.SP2

Traceback (most recent call last):
  File "OscScreenGrabLAN.py", line 199, in <module>
    depth = get_memory_depth(tn)
  File "/Users/mlemos/Google Drive/Projects/rigol/DS1054Z_screen_capture-master/Rigol_functions.py", line 52, in get_memory_depth
    mdep = h_grid \* scal \* srate
TypeError: can't multiply sequence by non-int of type 'str'

**Comment by RoGeorge** [comment]
Thank you for letting me know. There are 2 problems with v1.0.0 of the script. First, is that somehow I managed to push a broken version and tag it as the first release, v1.0.0. My bad here, sorry for that. Second is that different versions of oscilloscope firmware respond different to the same SCPI commands sent by the script.

As an example, the firmware version I have on my scope now, 00.04.03 SP1, is accepting commands without '\n' at the end. Other firmware versions seems to require a mandatory '\n' at the end of each command.

Also, 00.04.03 SP1 is adding 2 unexpected bytes at the end of the bitmap file. These two bytes does not follow the description of the BMP format, and does not follow the description of the response described in the Rigol's own manual. These 2 extra bytes can also be seen with Wireshark.

Long story short, this weekend I will try to fix all the reported issues:
- missing '\n'
- variable BMP length response
- broken CSV capture

**Comment by robindegen** [comment]
With the current master it worked just fine on OSX 10.12.6 for me. I used the default python 2 installation. Thank you for making this software, it's very useful!
